baseURL = "http://nitdelhi.acm.org/"
languageCode = "en-us"
title = "NIT Delhi ACM Student Chapter"

[params.og]
	title = "NIT Delhi ACM Student Chapter"
	image = "final.jpg"
	url = ""
	site_name = ""
	description = ""

[params.nav]

	[[ params.nav.item ]]

		title = "About Us"
		url = "/#aboutus"

	[[ params.nav.item ]]

		title = "Blog"
		url = "/blog"

	[[ params.nav.item ]]

		title = "Events"
		url = "/#events"

	[[ params.nav.item ]]

		title = "SIGs"
		url = "/#sigs"

	[[ params.nav.item ]]

		title = "Team"
		url = "/#team"

[params.hero]

	show = true

	[[ params.hero.list ]]

		title = "Welcome To !"
		description = "ACM Student Branch NIT DELHI"
		bgimg = "cs.jpg"

		url = "/#aboutus"
		btndesc = "About Us!"
	[[ params.hero.list ]]

		title = "Vision"
		description = "It's the community that shapes your knowledge"
		bgimg = "index.jpg"

		url = "/"
		btndesc = "Join Us!"

[params.about]

	show = true
	desc = "The National Institute of Technology Delhi ACM Student Chapter is an official student body incepted in 2019. Student Chapters provide unique opportunities for **Networking, Mentoring and Bonding** over **Common Interests**. The chapter organizes a number of events including programming contests, talks by renowned speakers, workshops etc. which give the students an exposure to the competitive computing world as well as allow them to understand the advancements going on in the Computing Sphere worldwide. The objective of the chapter to promote Computer Science as field of education and foster a sense of innovation and creativity among Computer Enthusiasts."


[params.services]

	show = true

	title = "Student Interest Groups"

	[[ params.services.list ]]
		
		title = "Competitive Programming"
		icon  = "icon-code"
		description = "Teach and Preach programming as a sport!"

	[[ params.services.list ]]
		
		title = "Web/App Development"
		icon  = "icon-laptop"
		description = "Build technologies for the people"

	[[ params.services.list ]]
		
		title = "Data Science"
		icon  = "icon-rocket"
		description = "AI is the next frontier in human ascension"

[params.members]

	show = true

	[[ params.members.list ]]

		name = "Dr. Anurag Singh"
		designation = "Faculty Sponsor"
		quote = ""
		avatar = "dranurag.jpg"
		linkedin = ""

	[[ params.members.list ]]

		name = "Vighnesh SK"
		designation = "Chairman"
		quote = ""
		avatar = "vignesh.jpg"

	[[ params.members.list ]]

		name = "Ajay Rathore"
		designation = "Vice Chairman"
		quote = ""
		avatar = "ajay.jpg"
	
	[[ params.members.list ]]

		name = "Mohit Sharma"
		designation = "Treasurer"
		quote = ""
		avatar = "mohit.jpg"

	[[ params.members.list ]]

		name = "Sushma Deegoju"
		designation = "Secretary"
		quote = ""
		avatar = "sushma.jpg"

	[[ params.members.list ]]

		name = "Aryan Garg"
		designation = "Web Master"
		quote = ""
		avatar = "aryan.jpg"
	
	[[ params.members.list ]]

		name = "Parvez Akhtar"
		designation = "Membership Chair"
		quote = ""
		avatar = "parvez.jpg"

[params.work]

	show = false

[params.blogpreview]

	show = false

[params.counter]

	show = false

	[[ params.counter.item ]]

		title = "Members"
		count = "12"

	[[ params.counter.item ]]

		title = "Projects"
		count = "2"

	[[ params.counter.item ]]

		title = "Research Papers"
		count = "0"

[params.testimony]

	show = false

[params.hire]

	show = false

[params.footer]

	email = "hello@nitdelhi.acm.org"

